### PR TITLE
Reformat CREATE TABLE statements for ease of reading

### PR DESCRIPTION
**Pull request by dougEfresh**

### CODE REVIEW

**Comment by VictorNine** [comment]
Good idea. But why the Travis change? Everything works with go 1.7

And the error handling is a bit redundant. The error will now be printed twice. I would remove the print from database.go and allow main to handle it like it was.

**Comment by dougEfresh** [comment]
I reverted to 1.7 in .travis
As for the error message, I want to show which SQL failed. In this case which table failed. 
The original error from sql lite doesn't tell you a lot about which SQL failed. I added a custom wrapper to include the SQL. 
Lastly, I've removed printing to STDERR. 

Thanks.

**Comment by VictorNine** [comment]
I still have some readability issues with this. Why not just "return errors.New(...)".  Line 54-62 can then be removed and the error can be handled by the caller.

**Comment by dougEfresh** [comment]
Totally forgot about errors.New.
I've updated using that method.

**Comment by VictorNine** [comment]
I was going to merge this but just saw that CREATE TABLE IF NOT EXISTS is missing and you have done some chase changes.

**Comment by VictorNine** [comment]
I was going to merge but saw that "CREATE TABLE IF NOT EXISTS" is missing and there has been some case changes. Please consider re-basing there are already 4 commits for this change.

**Comment by VictorNine** [comment]
Did you test this code?

./bitwarden-go -init returns:
```
2018/02/06 17:01:24 SQL error with 
CREATE TABLE IF NOT EXISTS "accounts" (
  id                 INT,
  name               TEXT,
  email              TEXT UNIQUE,
  masterpasswordhash NUMERIC,
  masterpasswordhint TEXT,
  KEY                TEXT,
  refreshtoken       TEXT,
  privatekey         TEXT NOT NULL,
  pubkey             TEXT NOT NULL,
PRIMARY KEY(id)
)

duplicate column name:  
```
And case is still wrong for some colums

**Comment by dougEfresh** [comment]
The IF NOT EXISTS in the create table prevented me from testing. I removed locally my db and it works.

**Comment by dougEfresh** [comment]
If we make the -init option exit, we can have travis run:
 go run cmd/bitwarden-go/main.go -init
to verify the SQL

**Pull request merged**
